name: lxd
version: 2.0.0.rc2-1
vendor: "Stéphane Graber <stgraber@ubuntu.com>"
icon: meta/lxd.png
type: framework
architectures: [amd64, armhf]
source: https://github.com/lxc
services:
 - name: lxd
   description: "The LXD container lightervisor"
   start: wrappers/lxd.start
   stop: wrappers/lxd.stop
   security-policy:
    apparmor: meta/lxd.apparmor
    seccomp: meta/lxd.seccomp
   ports:
    external:
     lxd:
      port: 8443/tcp
      negotiable: no
binaries:
 - name: wrappers/lxc
   description: "LXD command line client"
   caps:
    - networking
